## xval_mixed.R - cross-validation of caverify 0.2.0 mixed-level support
## against package CAs (U. Groemping), two ways:
##
##   Track A: arrays generated by CAs's own constructions (MCA2, MCAt,
##            projBoseMCA, CA_to_MCA), verified by ca_verify and by
##            CAs::coverage, plus randomized row-deletion mutations of
##            each array, with exact agreement required on the verdict,
##            the number of gapped column sets, and the number of
##            missing tuples.
##   Track B: randomized mixed-level matrices (every column attaining
##            all its symbols, no NAs), same exact-agreement contract.
##   Track C: NA wildcard semantics. caverify treats NA as "every
##            symbol of its column"; CAs::coverage ignores rows that
##            have an NA inside the projection. These differ BY DESIGN,
##            so NA arrays are checked against a pure-R brute-force
##            oracle with wildcard semantics, and the caverify/coverage
##            divergence is demonstrated, not equated.
##
## Contract for strict comparison (Tracks A and B): NA-free arrays,
## 0-based consecutive symbols, every column attains all its symbols
## (CAs derives level counts from the data, so this is the
## apples-to-apples contract).
##
## Run from the Spectre folder:  Rscript ca-tools/r/xval_mixed.R [NB]
## where NB (default 3000) is the number of Track B random cases.
## Expected final line: "XVAL PASS" (plus a case-count summary).

NB <- {
    a <- commandArgs(TRUE)
    if (length(a) >= 1) as.integer(a[1]) else 3000L
}

suppressMessages({
    library(caverify)
    if (!requireNamespace("CAs", quietly = TRUE))
        stop("package CAs is not installed; install it first ",
             "(remotes::install_github(\"ugroempi/CAs\"))")
    library(CAs)
})
cat("caverify ", as.character(packageVersion("caverify")),
    ", CAs ", as.character(packageVersion("CAs")),
    ", R ", R.version.string, "\n", sep = "")
stopifnot(packageVersion("caverify") >= "0.2.0")

ncase <- 0L; nfail <- 0L; nskip <- 0L

## ---- helpers ----

## strict three-number agreement with CAs::coverage on an NA-free array
compare_one <- function(x, t, vs, label = "") {
    ncase <<- ncase + 1L
    r <- ca_verify(x, t, v = vs)
    cv <- CAs::coverage(x, t, verbose = 1)
    ok <- identical(isTRUE(r$covered), isTRUE(all(cv$ncovereds == cv$tots))) &&
        r$colsets == choose(ncol(x), t) &&
        r$gaps == sum(cv$ncovereds < cv$tots) &&
        r$missing_tuples == sum(cv$tots - cv$ncovereds)
    if (!ok) {
        nfail <<- nfail + 1L
        cat("MISMATCH [", label, "]: N=", nrow(x), " k=", ncol(x), " t=", t,
            " vs=", paste(vs, collapse = ","), "\n", sep = "")
        cat("  caverify: covered=", r$covered, " gaps=", r$gaps,
            " missing=", r$missing_tuples, "\n", sep = "")
        cat("  coverage: gaps=", sum(cv$ncovereds < cv$tots),
            " missing=", sum(cv$tots - cv$ncovereds), "\n", sep = "")
    }
    invisible(ok)
}

## pure-R brute-force oracle with wildcard semantics (shares no logic
## with the C code); for Track C
brute_mixed <- function(x, t, vs) {
    k <- ncol(x); miss <- 0; gaps <- 0
    combs <- utils::combn(k, t)
    for (ci in seq_len(ncol(combs))) {
        cols <- combs[, ci]
        tuples <- as.matrix(expand.grid(lapply(cols, function(cc) 0:(vs[cc] - 1))))
        sub <- x[, cols, drop = FALSE]
        hit <- logical(nrow(tuples))
        for (r in seq_len(nrow(sub))) {
            row <- sub[r, ]
            ok <- rep(TRUE, nrow(tuples))
            for (j in seq_len(t)) {
                if (!is.na(row[j])) ok <- ok & (tuples[, j] == row[j])
            }
            hit <- hit | ok
        }
        if (!all(hit)) { gaps <- gaps + 1; miss <- miss + sum(!hit) }
    }
    list(covered = gaps == 0, gaps = gaps, missing = miss)
}

## a construction array plus mutations, all strictly compared
check_construction <- function(D, t, label, nmut = 30L) {
    D <- unclass(as.matrix(D)); attributes(D) <- attributes(D)["dim"]
    storage.mode(D) <- "integer"
    if (any(is.na(D))) {
        ## flexible values: wildcard semantics, oracle track only
        vs <- apply(D, 2, function(cc) length(setdiff(unique(cc), NA)))
        if (choose(ncol(D), t) * prod(sort(vs, decreasing = TRUE)[1:t]) <= 20000 &&
            nrow(D) <= 200) {
            ncase <<- ncase + 1L
            r <- ca_verify(D, t, v = as.integer(vs))
            b <- brute_mixed(D, t, as.integer(vs))
            if (!(identical(isTRUE(r$covered), b$covered) &&
                  r$gaps == b$gaps && r$missing_tuples == b$missing)) {
                nfail <<- nfail + 1L
                cat("MISMATCH vs oracle [", label, " (NA)]\n", sep = "")
            }
        } else nskip <<- nskip + 1L
        return(invisible(NULL))
    }
    if (min(D) != 0) D <- D - min(D)   ## defensive; constructions are 0-based
    vs <- apply(D, 2, function(cc) length(unique(cc)))
    ## sanity: consecutive 0-based symbols per column (the strict contract)
    if (!all(apply(D, 2, max) == vs - 1)) { nskip <<- nskip + 1L; return(invisible(NULL)) }
    vs <- as.integer(vs)
    ## the array itself: the construction promises coverage
    ncase <<- ncase + 1L
    r <- ca_verify(D, t, v = vs)
    if (!isTRUE(r$covered)) {
        nfail <<- nfail + 1L
        cat("CONSTRUCTION NOT COVERED by ca_verify [", label, "]\n", sep = "")
    }
    compare_one(D, t, vs, paste0(label, " full"))
    ## randomized mutations: delete rows until agreement is tested on
    ## broken arrays too
    for (m in seq_len(nmut)) {
        ndel <- sample(1:max(1, nrow(D) %/% 3), 1)
        keep <- sort(sample(nrow(D), nrow(D) - ndel))
        Dm <- D[keep, , drop = FALSE]
        ## keep the strict contract: every column still attains all symbols
        if (!all(apply(Dm, 2, function(cc) length(unique(cc))) == vs)) next
        compare_one(Dm, t, vs, paste0(label, " mut", m))
    }
}

set.seed(20260823)

## ---- Track A: her constructions ----
cat("--- Track A: CAs constructions ---\n")
tryA <- function(expr, t, label) {
    D <- tryCatch(expr, error = function(e) {
        cat("skip [", label, "]: ", conditionMessage(e), "\n", sep = "")
        nskip <<- nskip + 1L; NULL
    })
    if (!is.null(D)) check_construction(D, t, label)
}

## MCA2: strength-2 mixed constructions over random level profiles
for (i in 1:12) {
    k <- sample(4:7, 1)
    prof <- sort(sample(2:6, k, replace = TRUE), decreasing = TRUE)
    tryA(MCA2(prof, outerRetry = 0, seed = 1000 + i), 2,
         paste0("MCA2 ", paste(prof, collapse = ",")))
}

## projBoseMCA: two-level-count profiles from the documentation family
for (prof in list(c(rep(4, 6), 6), c(rep(6, 8), 8), c(rep(2, 3), 4),
                  c(rep(4, 4), 3), c(rep(6, 6), 5))) {
    tryA(projBoseMCA(prof), 2,
         paste0("projBoseMCA ", paste(prof, collapse = ",")))
}

## CA_to_MCA: reduce levels of best known uniform CAs
tryA(CA_to_MCA(bestCA(2, 6, 3), cs = 5:6, tolevs = c(2, 2), t = 2,
               outerRetry = 0, seed = 42), 2, "CA_to_MCA t2")
tryA(CA_to_MCA(bestCA(3, 6, 3), cs = 4:6, tolevs = rep(2, 3), t = 3,
               outerRetry = 0, seed = 42), 3, "CA_to_MCA t3")

## MCAt: strength-3 mixed construction
tryA(MCAt(c(4, 4, 3, 2, 2, 2), 3, outerRetry = 0, seed = 42), 3,
     "MCAt 4,4,3,2,2,2")

## uniform sanity anchor: KSK strength-2 two-level CA
tryA(KSK(k = 10), 2, "KSK k=10")

## ---- Track B: randomized mixed-level matrices ----
cat("--- Track B: randomized matrices ---\n")
for (i in seq_len(NB)) {
    k <- sample(3:8, 1)
    t <- sample(2:min(4, k - 1), 1)
    vs <- sample(2:5, k, replace = TRUE)
    N <- sample(max(vs):60, 1)
    x <- sapply(vs, function(v) c(sample(0:(v - 1)),
                                  sample(0:(v - 1), N - v, replace = TRUE)))
    x <- x[sample(nrow(x)), , drop = FALSE]
    compare_one(x, t, as.integer(vs), paste0("rand", i))
}

## ---- Track C: NA wildcard semantics ----
cat("--- Track C: NA wildcards vs oracle ---\n")
for (i in 1:200) {
    k <- sample(3:5, 1); t <- sample(2:min(3, k), 1)
    vs <- sample(2:4, k, replace = TRUE)
    N <- sample((max(vs) + 1):15, 1)
    x <- sapply(vs, function(v) c(sample(0:(v - 1)),
                                  sample(0:(v - 1), N - v, replace = TRUE)))
    x[sample(length(x), sample(1:3, 1))] <- NA
    ncase <- ncase + 1L
    r <- ca_verify(x, t, v = as.integer(vs))
    b <- brute_mixed(x, t, as.integer(vs))
    if (!(identical(isTRUE(r$covered), b$covered) &&
          r$gaps == b$gaps && r$missing_tuples == b$missing)) {
        nfail <- nfail + 1L
        cat("MISMATCH vs oracle [NA rand", i, "]\n", sep = "")
    }
}
## demonstrate the documented caverify/coverage divergence on NA
plan <- cbind(rep(0:2, each = 3), c(rep(0:1, 4), 1), c(rep(0:1, each = 4), 0))
fixd <- rbind(plan[-(1:2), ], c(NA, NA, NA))
r <- ca_verify(fixd, 2, v = c(3L, 2L, 2L))
cv <- CAs::coverage(fixd, 2, verbose = 1)
div_ok <- isTRUE(r$covered) && any(cv$ncovereds < cv$tots)
cat(sprintf("NA-divergence demo as documented (wildcard vs ignored): %s\n", div_ok))
if (!div_ok) nfail <- nfail + 1L

## ---- summary ----
cat(sprintf("cases: %d, mismatches: %d, skipped: %d\n", ncase, nfail, nskip))
if (nfail == 0L) cat("XVAL PASS\n") else cat("XVAL FAIL\n")
